vignettes/examples/variational_autoencoder.R

setting up variational autoencoder
not ready to merge

variational autoencoder

---

docs/articles/examples/variational_autoencoder.R
vignettes/examples/variational_autoencoder.R

Changed the range for the 2D manifold visualization from +/- 15 standard deviations to +/- 4 standard deviations, because it gives a better representation of the manifold space.  It is possible to see all the numbers and the transitions between them in the space.   I posted examples of the difference in the visualizations - here: https://github.com/rstudio/keras/issues/48#issuecomment-310877166

Changed sample point range for 2D manifold visualization

---

DESCRIPTION
R/history.R

This PR contains a version of the `plot.keras_training_history` function. There is two main changes: there is now a `ggplot2` method, and the base method now takes validation metrics into account when calculating the y-range.
The code for the base plot has changed a bit, partly to fix the bug and partly to factor out common tasks between the two methods.
I have added `ggplot2` to Suggests.
```
data(iris)
m <- keras_model_sequential() %>%
layer_dense(12, input_shape = 4) %>%
layer_dense(4, activation = 'sigmoid') %>%
compile('adam', 'categorical_crossentropy', 'accuracy')
m2 <- m
h <- fit(m, as.matrix(iris[1:4]), to_categorical(iris[[5]]), 8, 100, validation_split = 0.2)
h2 <- fit(m2, as.matrix(iris[1:4]), to_categorical(iris[[5]]), 8, 50)
```
History `h` has validation data, `h2` does …

Fixed y-range issue (#54), and added ggplot method.

---

R/history.R

This PR resolves issue [#117](https://github.com/rstudio/keras/issues/117#issuecomment-326672778). The issue being that plotting of training history would fail when early stopping was used. 
The fix was to pad the training metrics with NAs so that the number of rows is the same as the specified number of training epochs, not the number that occurred before early stopping.
Now when plotting the training history after early stopping we get a plot like this:
There are few things I am a little unsure of:
1. The fix uses NAs which causes the following warning messages to be displayed when calling the `plot()` function:
```
Warning messages:
1: Removed 352 rows containing non-finite values (stat_smooth). 
2: Removed 352 rows containing missing values (geom_point). 
```
Should we hide these or …

Fix error when plotting training history after early stopping.

---

vignettes/examples/deep_dream.R
vignettes/examples/neural_style_transfer.R
vignettes/examples/variational_autoencoder.R
vignettes/examples/variational_autoencoder_deconv.R

@dfalbel I attempted here to modify the neural style example to use 1-based indexing. However, when I source the script I get this error:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
ValueError: cannot reshape array of size 1366800 into shape (1,) 
20. stop(structure(list(message = "ValueError: cannot reshape array of size 1366800 into shape (1,)", 
call = py_call_impl(callable, dots$args, dots$keywords), 
cppstack = structure(list(file = "", line = -1L, stack = c("1   reticulate.so                       0x000000010b5f82a4 _ZN4Rcpp9exceptionC2EPKcb + 276", 
"2   reticulate.so                       0x000000010b5f80d0 _ZN4Rcpp4stopERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 48",  ... 
19. _wrapfunc at fromnumeric.py#57
18. reshape at …
```

change nueral style transfer indexes to 1-based

---

R/model-persistence.R

`cloudml` seems to expect the signature `method_name` to be set. Otherwise, once the keras model is exported using `export_savedmodel()` and uploaded to cloudml using `cloudml::cloudml_deploy()`, predictions in `cloudml` using `cloudml::cloudml_predict()` fails with error:
```
Error in cloudml::cloudml_predict(list(list(input = array(0, c(32, 32,  : 
Prediction failed: Error during model execution: AbortionError(code=StatusCode.INTERNAL, details="Expected prediction signature method_name to be one of {tensorflow/serving/predict, tensorflow/serving/classify, tensorflow/serving/regress}. Was: ")
```

Enable predictions in cloudml from savedmodels

---

R/model-persistence.R

While testing `export_savedmodel()` under TensorFlow 1.4.0, a special case was introduced; however, in 1.4.1 this behavior seems reverted and the special case introduced in 1.4.0 is no longer necessary since it exports models incorrectly. Also, under the tensorflow-keras implementation, not all fields were available using the same identifiers.

Remove workaround for export_savedmodel fixed in tf 1.4.1

---

R/model-persistence.R

Found models (like [/models/keras-multiples.R](https://github.com/rstudio/tfdeploy/blob/master/tests/testthat/models/keras-multiples.R)) where `export_savedmodel()` was not producing the right naming.

export_savedmodel() to support multiple inputs and outputs

---

vignettes/examples/variational_autoencoder.R

This change always the sampling function to work correctly for latent dimensions other than 2.  This also matches the code for the variational_autoencoder_deconv.

Added latent_dim to sampling function on variational_autoencoder example

---

NEWS.md
R/model-persistence.R

Run `https://github.com/rstudio/cloudml/blob/master/inst/examples/keras/mnist_mlp.R`, then run:
```r
export_savedmodel(model, "savedmodel")
```
The export succeeds but contains a `learning_phase` placeholder, this PR follows the suggestion on https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html to set `learning_phase(0)` and reload the model before exporting.

Support learning phases in `export_savedmodel()`

---

R/layers-dropout.R
R/layers-recurrent.R

* Inserts space in layer_lstm roxygen notes.
* Removes word python from layer_dropout.

Fixes typos in two functions

---

NEWS.md
R/backend.R

I am not sure why but the following doesn't work:
```
p <- k_placeholder(shape = shape(NULL, 1, 1, NULL, 8))
k_tile(p, c(1, 1, 10, 1, 1))
Error in py_call_impl(callable, dots$args, dots$keywords) : 
ValueError: Shape must be rank 1 but is rank 2 for 'Tile_3' (op: 'Tile') with input shapes: [?,1,1,?,8], [1,5].
``` 
And this works (ie. removing the call for `list`):
```
K$tile(x = p, n = as.integer(c(1, 1, 10, 1, 1)))
Tensor("Tile_5:0", shape=(?, 1, 10, ?, 8), dtype=float32)
```

tile uses an integer vector not a list

---

R/preprocessing.R

- Fix typo in the `target_size` description.
Closes  #469

Fixes typo in an argument description

---

index.Rmd
pkgdown/_pkgdown.yml
vignettes/eager_guide.Rmd
vignettes/getting_started.Rmd
vignettes/guide_keras.Rmd

Something I wasn't aware of before: that you need to convert to tensor before getting predictions in case you've restored weights for a model that's never been called (because the test data now have to provide shape information).
I'm showing 2 ways which I think is okay - the iterator way would be necessary anyway if one had bigger test sets... but for the other, do you think I'd better leave it out (to avoid confusion)?
Alternatively, I wonder if it makes sense to have something like `as_tensor` that more clearly indicates the intent (afaik we don't have that right?)?

add eager guide

---

R/model.R

This just duplicates the code of course, but perhaps is the safest way at the moment?
(Assuming one could be removed later some time....)
Or should we query which is used and set a variable for that?
fix for https://github.com/rstudio/keras/issues/225

newer versions use keras_preprocessing module name

---

R/utils.R

With TF nightly, where
```
> keras:::keras_version()
[1] ‘2.2.4’
```
`keras_array()` always fails at https://github.com/rstudio/keras/commit/42b09e9fe14ad334d0b74c850f01b1a705839aee#diff-cbb7235afee10c3646161358a7655b0aR223 since `k_is_tensor()` doesn't work with the TF backend.

Fix is_tensor checking in keras_array()

---

NEWS.md
R/package.R
inst/python/kerastools/layer.py
inst/python/kerastools/model.py
inst/python/kerastools/wrapper.py
tests/testthat/test-model-persistence.R

In addition to what we said, I had to set 
```
KERAS_IMPLEMENTATION = "tensorflow"
```
somewhere, because the Python classes need it:
```
if (os.getenv('KERAS_IMPLEMENTATION', 'keras') == 'tensorflow'):
```
LMK if there's a better place than line 91/92 where I'm doing it (tried various ways of doing this as a side effect from called methods but that failed on package load, this is why I'm doing it there.)
With that change, all tests pass (TF 1.x only, so far). 
The update to NEWS.md is just "improvised", but it seems we also have to rethink version numbering, now that we basically depend on TF releases...

switch to tf.keras as default implementation

---

R/utils.R

This actually fixes all but 4(!!!) tests against today's 2.0 preview... tried to be conservative changing `keras_array` so hopefully should run against all required versions/implementations/backends (tested 1.12 and 1.13 and `module(keras)`...
The remaining 4 tests are all model saving / `tfruns` related, so it seems `keras` is in pretty good shape already ...

factor out is_keras_tensor due to 2.0

---

tests/testthat/test-generators.R

Turns out that `2. Failure: image data generator can be used for training ` was a simple metric name change.

fix test that was making image_data_generator fail on 2.0

---

R/callbacks.R
R/model.R
appveyor.yml
inst/python/kerastools/callback.py
man/callback_lambda.Rd
man/evaluate.keras.engine.training.Model.Rd
man/evaluate_generator.Rd
man/predict.keras.engine.training.Model.Rd
man/predict_generator.Rd
tests/testthat/test-callbacks.R
vignettes/training_callbacks.Rmd

Related to #712 .
It will take more time that I have imagined will and only work with tf-2.0 so I think it's better to wait until tf-1.13.1 is on CRAN.
- Dealing with tf versions lower than 2.0
- Add a  `callbacks` parameter to `evaluate`,  `predict_generator`, etc.
- Add tests for them

Add new callbacks moments

---

NEWS.md
R/utils.R

Allowing data.frames will be useful to use the `layer_dense_features` without having to converto the df to a list.

Allow passing dataframes to fit and etc.

---

.travis.yml
NEWS.md
R/install.R
R/model.R
tests/testthat/test-tfdatasets.R

Make `fit` compatible with tfdatasets with 1.14 when using `tf.distribute`. fixes #855

directly pass the dataset in 1.14

---

R/model-custom.R

Changes in reticulate have fixed the issue without named args - which triggered the need for `py_func`

py_func call is no longer necessary

---

R/layers-core.R
R/model.R
tests/testthat/test-model.R

This PR enables passing additional arguments when calling a model. This enable something like:
```
model <- keras_model_sequential() %>% 
layer_dropout(rate = 0.99999999)
model(1, training = TRUE)
model(1, training = FALSE)
```

Call model with additional args

---

.travis.yml

Showing the progress when installing via pip leaves us with this error in travis: 
> The job exceeded the maximum log length, and has been terminated.
https://travis-ci.org/rstudio/keras/jobs/610866714#L1079

Quiet pip on travis

---

R/applications.R
R/initializers.R
R/layers-features.R
R/optimizers.R
R/package.R
tests/testthat/test-layers.R
tests/testthat/test-preprocessing.R
tests/testthat/utils.R

See https://stackoverflow.com/questions/58279628/what-is-the-difference-between-tf-keras-and-tf-python-keras/58279629#58279629
@kevinykuo We were already using correct optmizerV2 for instance, but this will be important since they are changing a lot the API in `tf.python.keras` recently.

Using tf.keras instead of tf.python.keras

---

DESCRIPTION
R/layers-normalization.R
man/layer_batch_normalization.Rd

Have had a desire to use renorm from the R side with layer_batch_normalization, so simply exposed them in the function args and create_layer call.

expose renorm, renorm_clipping to layer_batch_normalization

---

R/layer-text_vectorization.R
inst/python/kerastools/get_vocabulary.py

`get_vocabulary` is very slow in R because it returns byte strings which are not directly handled by reticulate. 
With this PR we convert the byte strings  to UTF8 using `.decode` before passing to R, making it much faster.

get_vocabulary performance

---

inst/python/kerastools/callback.py

While trying to get distributed training to work as follows hitting the following error, see also [mlverse/distributed](https://github.com/mlverse/distributed) repo.
```r
Sys.setenv(TF_CONFIG = jsonlite::toJSON(list(
cluster = list(
worker = c("172.17.0.6:10090", "172.17.0.3:10088", "172.17.0.4:10087", "172.17.0.5:10089")
),
task = list(type = 'worker', index = 0)
), auto_unbox = TRUE))
Sys.setenv(TF_CONFIG = jsonlite::toJSON(list(
cluster = list(
worker = c("172.17.0.6:10090", "172.17.0.3:10088", "172.17.0.4:10087", "172.17.0.5:10089")
),
task = list(type = 'worker', index = 1)
), auto_unbox = TRUE))
Sys.setenv(TF_CONFIG = jsonlite::toJSON(list(
cluster = list(
worker = c("172.17.0.6:10090", "172.17.0.3:10088", "172.17.0.4:10087", "172.17.0.5:10089")
),
task = list(type = 'worker', index …
```

Need fix to use distributed training with keras

---

R/model.R

The main description (and code) say 1-based, but @param still said 0-based.

Small typo in get_layer documentation

---

.github/workflows/main.yaml
NEWS.md
R/applications.R
R/callbacks.R
R/history.R
R/install.R
R/metrics-callback.R
R/model.R
tests/testthat/test-callbacks.R

This  reimplements the metrics callbacks when using TF 2.2 since breaking changes in how parameters are passed to callbacks.
See here for more info: https://github.com/tensorflow/tensorflow/issues/38512

Fixes metric callbacks with TF 2.2

---

R/model.R
man/keras_model.Rd
tests/testthat/test-model.R

Hi. Should it be added to Functional API? I looked at https://www.tensorflow.org/api_docs/python/tf/keras/Model and saw that Functional API has ```**kwargs```. PR is based on https://github.com/rstudio/keras/issues/1044
```
tf.keras.Model(
*args, **kwargs
)
```

Update "keras_model" in model.R

---

R/install.R

Fix this error:
https://github.com/rstudio/keras/runs/828835224?check_suite_focus=true#step:9:280
Fix #1078

don't install scipy as it's already installed by tensorflow

---

man-roxygen/roxlate-recurrent-layer.R

Added a couple notes to the `roxlate-recurrent-layer.R` template/documentation:
1. Use `NULL` for dimension sizes that are not known ahead of time (with example)
2. Link to a blog post I found helpful for understanding the `stateful` parameter. May help others too. @dfalbel may not be general enough for what you had in mind?
These correspond to the two commits included. I didn't rebuild the `.Rd` files&mdash;is it best practice to include the rebuild in the PR? I have a later version of `roxygen` and found that more changed than just those files which use the `roxlate-recurrent-layer` template.
Fixes #902.

RNN `stateful` parameter documentation

---

R/model.R
man/multi_gpu_model.Rd

Adresses #1093:
- Docs: Added a `@note` mentioning the deprecation (see https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy) and provided a minimal example of using `tensorflow::tf$distribute$MirroredStrategy()` as an alternative implementation
- Added a check for tensorflow 2.2 to raise an error if used with the current version of tensorflow or greater:
```r
if (tensorflow::tf_version() >= "2.2")
stop("This function is deprecated as of TF version 2.2")
```
Please note that I am not certain how these kinds of deprecations are usually handled, I'm still very new to keras and tensorflow, so I'm happy to adjust the PR as needed.

Add deprecation warning & alternative solution for multi_gpu_model()

---

R/preprocessing.R
man/text_one_hot.Rd

The argument was renamed from `text` to `input_text` in TF >= "2.3"

Text one hot

---

R/preprocessing.R
tests/testthat/test-preprocessing.R

Right now: 
``` r
keras::text_hashing_trick(NA_character_, 5)
#> [1] 4
```
<sup>Created on 2020-05-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
which seems wrong. This PR just returns a `NA_integer_`:
``` r
keras::text_hashing_trick(NA_character_, 5)
#> [1] NA
```
<sup>Created on 2020-05-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
It also gives an informative error when `text` is not a scalar.

Missing text when hashing

---

R/backend.R

add an error message pointing to TensorFlow implementation
Fix #1120

logsumexp was removed from the Keras backend 

---

R/preprocessing.R
man/flow_images_from_dataframe.Rd
tests/testthat/test-preprocessing.R

With tensorflow 2.3 drop_duplicates in flow_images_from_dataframe gives a DeprecationWarning:
``` r
library(keras)
library(tensorflow)
library(imager)
library(dplyr)
reticulate::use_condaenv("tf_2.3", required = TRUE)
tf_version()
#> [1] '2.3'
packageVersion("keras")
#> [1] '2.3.0.0'
minst_data <- tf$keras$datasets$mnist$load_data()
n_imgs <- 1000 # Use 1000 test images
minst_meta <- data.frame(file = paste0("minst_sample/imgs/img_", 1:n_imgs, ".png"),
class = paste0("N_", minst_data[[2]][[2]][1:n_imgs]))
dir.create("minst_sample/imgs/", recursive = TRUE, showWarnings = FALSE)
for(i in 1:n_imgs) {
imager::save.image(imager::as.cimg(minst_data[[2]][[1]][i,,]),
file = minst_meta$file[i])
}
rm(i, minst_data, n_imgs)
write.csv(minst_meta, file="minst_sample/minst_meta.csv", row.names = FALSE) …
```

Fix drop_duplicates DeprecationWarning with tf 2.3

---

R/preprocessing.R

Hi,
due to the way @dfalbel changed my pull request #1139, the DeprecationWarning from tensorflow will still be shown (along with the R one). This is because even though in creation of the `args` list the `drop_duplicates` element is set to `NULL`, its still an element of `args`. See this minimal example:
``` r
drop_duplictaes = NULL
args <- list(drop_duplictaes = drop_duplictaes)
print(args)
#> $drop_duplictaes
#> NULL
args$drop_duplictaes <- NULL
print(args)
#> named list()
```
<sup>Created on 2020-11-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
As shown in the example, setting `drop_duplicates` to  `NULL`after the creation of `args` will actually remove the `drop_duplicates` element and, hence, get rid of the DeprecationWarning from tensorflow (not 100% …

Correction to merged PR #1139

---

R/utils.R
tests/testthat/test-utils.R

It seems that HDF5Matrix has been removed from Keras in TF 2.4.
It used to be an utility but can't be found anymore here: https://keras.io/api/utils/

hdf5 has been removed in tf 2.4

---

R/install.R

Currently nightly is failing installation because it seems impossible to match the dependencies.

Fix TF Nightly installation

---

DESCRIPTION
R/package.R

Keras implementation is no longer maintained in favor of tensorflow's and we should warn users that are still setting that.

warning for keras implementations != than tensorflow.

---

R/metrics-callback.R
R/model-legacy.R
R/model.R
inst/python/kerastools/generator.py
inst/python/kerastools/model.py
man/evaluate.keras.engine.training.Model.Rd
man/fit.keras.engine.training.Model.Rd
man/predict.keras.engine.training.Model.Rd
man/predict_on_batch.Rd
man/predict_proba.Rd
tests/testthat/helper-utils.R
tests/testthat/test-callbacks.R
tests/testthat/test-generators.R
tests/testthat/test-preprocessing.R
tests/testthat/test-timeseries.R

This fixes the problem of calling generators from different threads. Essentially what we do is:
1. Instead of passing the R generator, we pass a dummy generator that just reads elements from a queue.
2. The queue is updated by a callback that runs the R generator before the data is actually requested by `fit`/`predict`/`evaluate`.
This works because callbacks are executed in the main thread and we no longer need to execute R code from background threads.
User might see a warning:
> WARNING:tensorflow:Callback method `on_train_batch_begin` is slow compared to the batch time (batch time: 0.0007s vs `on_train_batch_begin` time: 0.0012s). Check your callbacks.
This is expected because it's `on_train_batch_begin` that the R generator is evaluated.
Fixes #986 
Fixes #1104

Fit generator

---

R/install.R
man/install_keras.Rd

At the moment,  `?keras3::install_keras` directs the user to set argument `backend = "pytorch"` if *PyTorch* should be used as backend. 
However, calling `keras3::install_keras(backend = "pytorch")` results in the following error when the install script tries to install python library `pytorch` instead of `torch`.
```R
Building wheels for collected packages: pytorch
Building wheel for pytorch (setup.py): started
Building wheel for pytorch (setup.py): finished with status 'error'
error: subprocess-exited-with-error
× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File …
```

Updating documentation of install_keras for argument backend: changing "pytorch" to "torch" so that installs with backend PyTorch do not fail

---

NEWS.md
R/install.R

Updates for Keras 3.4.1. This will be released to CRAN once confirmed to work with the upcoming TensorFlow 2.17.0 release.

Retether-3.4.1

---

R/install.R

This is my fix of issue #1509. As also explained in the bug report, the function logic regarding "Linux installing GPU-enabled tensorflow-backend" fails to install the GPU version, but only with CPU.
I have added a "if-else" block to check if "tensorflow" was the only backend requested GPU on Linux. If so, we install tensorflow with GPU support. Otherwise, i.e. there are multiple backends requested (as tensorflow is always enabled), we need to install only the CPU version of tensorflow.
Thanks!

fix issue [#1509](https://github.com/rstudio/keras3/issues/1509)
