docs/articles/examples/variational_autoencoder_deconv.R, docs/articles/examples/variational_autoencoder_deconv.html, vignettes/examples/index.Rmd, vignettes/examples/variational_autoencoder_deconv.R
Example for building a variational autoencoder using deconvolutions. This is an R translation of https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder_deconv.py
=> Added example for variational autoencoder using deconvolutions

vignettes/examples/addition_rnn.R, vignettes/examples/babi_memnn.R, vignettes/examples/cifar10_cnn.R
_addition_rnn.R:_
Reformatted file, fixing any grammar and spelling mistakes I noticed. Also restructured some sentences for improved flow and overall consistency.
_babi_memnn.R:_
Similar to above, mostly just reformatting; no real content changes
_cifar10_cnn.R:_
Noted the feature scaling applied to the input images' RGB values. Also added some documentation of the model initialization similar to what is seen [here](https://github.com/rstudio/keras/blob/master/vignettes/examples/imdb_cnn_lstm.R).
=> Minor changes to first 3 vignette/examples

vignettes/examples/conv_lstm.R, vignettes/examples/deep_dream.R, vignettes/examples/imdb_bidirectional_lstm.R, vignettes/examples/imdb_cnn.R
Nothing all that extraordinary, something of a part two to my previous formatting commit. Will do the remaining examples in similar batches as I find the time.
=> Formatting for additional vignettes/examples

vignettes/examples/imdb_cnn_lstm.R, vignettes/examples/imdb_fasttext.R, vignettes/examples/imdb_lstm.R, vignettes/examples/lstm_text_generation.R, vignettes/examples/mnist_acgan.R, vignettes/examples/mnist_antirectifier.R, vignettes/examples/mnist_cnn.R, vignettes/examples/mnist_hierarchical_rnn.R, vignettes/examples/mnist_irnn.R, vignettes/examples/mnist_mlp.R, vignettes/examples/mnist_tfrecord.R
Lots of format improvements and improved consistency between examples. 
_Code Modification_:
imdb_cnn_lstm.R - removed comment displaying format of code and added str(imdb) so user can simply view it in their window. Improves flow of example and explanations of variables are still present above.
=> Next Example Format Batch

vignettes/examples/neural_style_transfer.R
It turns out that I was using `as.numeric` to reshape an array to a 1d array, and it works column major instead of row major as array_reshape.
This PR fixes the neural style example. I'll still fix the other examples to the TF changes this week.
=> Correcty array reshaping in neural style example

vignettes/examples/deep_dream.R, vignettes/examples/variational_autoencoder.R, vignettes/examples/variational_autoencoder_deconv.R
I think that with this, all examples working with the new R-like indexing in TF.
=> R-like indexing for all examples

vignettes/examples/cifar10_densenet.R, vignettes/examples/cifar10_densenet.Rmd
Example discussed at #138 
Let me know what you think!
=> densenet example

R/model-persistence.R, man/export_savedmodel.keras.engine.training.Model.Rd, tests/testthat/test-model-persistence.R
See https://github.com/rstudio/tfdeploy/issues/2
=> Implement new export_savedmodel params

vignettes/examples/quora_siamese_lstm.R, vignettes/examples/quora_siamese_lstm.Rmd
@jjallaire Does it make sense to also add this script here?
=> Example quora_siamese_lstm

DESCRIPTION, NEWS.md, R/model-persistence.R, man/layer_dropout.Rd, man/layer_lstm.Rd
See https://github.com/rstudio/keras/issues/274, some models do not require `learning_phase` to be removed.
=> Add support to not remove learning phase

vignettes/faq.Rmd
Closes https://github.com/rstudio/keras/issues/322
=> update bibtex citation to reflect R package

DESCRIPTION, NEWS.md, R/applications.R, R/backend.R, R/callbacks.R, R/layers-convolutional.R, R/layers-core.R, R/model.R, R/preprocessing.R, man/application_nasnet.Rd, man/callback_reduce_lr_on_plateau.Rd, man/callback_remote_monitor.Rd, man/image_data_generator.Rd, man/imagenet_preprocess_input.Rd, man/k_softmax.Rd, man/layer_conv_2d.Rd, man/layer_depthwise_conv_2d.Rd, man/layer_flatten.Rd, man/layer_separable_conv_1d.Rd, man/layer_separable_conv_2d.Rd, man/multi_gpu_model.Rd, man/text_hashing_trick.Rd, man/text_one_hot.Rd, man/text_to_word_sequence.Rd
=> changes for keras 2.1.6

NEWS.md, R/layers-core.R, R/utils.R
=> fixes #380, make sure output_shape is passed if supplied to layer_lambda

vignettes/examples/deep_dream.R
This updates the Deep Dream Example following the original [here](https://github.com/keras-team/keras/blob/master/examples/deep_dream.py).
This is also related to #397
=> Updating deep dream example

vignettes/examples/unet.R, vignettes/examples/unet_linux.R
https://github.com/rstudio/keras/issues/521
=> use custom_metric

vignettes/examples/eager_cvae.R, vignettes/examples/eager_cvae.Rmd
There'll be a second example still for the post, I'll add that to this PR later today.
=> add eager cvae example

R/utils.R
suggestion for https://github.com/rstudio/keras/issues/591
=> don't convert (list of) tf.keras tensors in keras_array

inst/python/kerastools/callback.py, inst/python/kerastools/constraint.py, inst/python/kerastools/progbar.py
Same as `layer.py`, `model.py` etc. (missed these because there are no tests for them)
=> further Python classes needing new tf.keras default

DESCRIPTION, R/backend.R, tests/testthat/test-backend.R
=> Fix k_set_epsilon() and k_set_floatx() for tensorflow

R/model.R
not yet a fix for #682 but I something I noticed on the way... adding corresponding test in `tfdatasets`.
=> fix fit_generator for tfdatasets

R/model.R, inst/python/kerastools/generator.py
Partial fix for #682 
Do not merge, there are still issues to surmount here.
This PR wraps R functions in a threadsafe Python generator, however the test still fails with an error similar to what is being reported here: https://github.com/rstudio/keras/issues/33#issuecomment-470490670
=> Wrap R functions in a custom generator

.travis.yml
Trying to get reprex for https://github.com/rstudio/keras/pull/692#discussion_r266141261
=> Add TensorFlow 1.12/2.0 to Travis

DESCRIPTION, R/applications.R, man/application_mobilenet_v2.Rd
fix for https://github.com/rstudio/keras/issues/714
=> depth_multiplier was removed

vignettes/examples/quora_siamese_lstm.R
See https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs
=> Data download link changed

DESCRIPTION, man/keras-package.Rd
This branch has been tested with R tensorflow v1.13.1 from master on: 
- TF 1.13.1
- Windows
- Linux
- MacOS
- TF 1.12.0
- Windows
- Linux
- MacOS
All tests are passing on these platforms. 
I am now running the revdep checks.
=> CRAN release

.travis.yml, R/initializers.R, R/optimizers.R, man/initializer_variance_scaling.Rd, tests/testthat/test-callbacks.R
This will fix 2 Travis errors on 2.0:
> 3. Failure: model can be saved and loaded from json 
> 4. Failure: model can be saved and loaded from yaml 
TF 2.0 has introduced V2 implementation for all initialization ops and loading is not compatible with the older ones.
=> Fix for saving model to json and yaml

R/model.R
This is a WIP PR with fixes to make tfdatasets work with keras in TF 2.0
=> [WIP] Fixes for tfdatasets

R/package.R
=> Register class filters on package load not on module load

R/layers-core.R, tests/testthat/test-model.R
@dfalbel what we talked about... like so?
=> enable calling a model on R objects

.travis.yml, R/layers-core.R, R/model-custom.R, R/wrapper_custom.R
wrap around `reticulate::py_func`. This will fix #801
=> Fix for #801

.travis.yml, tests/testthat/test-custom_wrappers.R
=> Update tensorflow versions

NEWS.md, R/install.R, man/install_keras.Rd
adresses #808 by adding an ellipsis argument allowing to pass other a…
=> Additional arguments to install_keras (eg. envname)

R/layers-recurrent.R
corrected a typo in `layer_gru()` docs
=> corrected docs typo

NEWS.md, R/model.R, tests/testthat/test-generators.R
fixes #836 by transforming validation_data into a tuple as enforced by TF
=> Fix for #836

vignettes/examples/variational_autoencoder.R, vignettes/examples/variational_autoencoder_deconv.R
https://github.com/rstudio/keras/pull/923 fixed this, but I have overwritten while moving the docs too the new website. This PR closes https://github.com/rstudio/keras/issues/954
=> re-update the vae examples

R/backend.R
Again, PR is based on https://github.com/rstudio/keras/issues/1043.
Should we stop calling function because it throws an error?
=> Update get and set session

pkgdown/extra.js
@javierluraschi --
Here's the extra.js file expanded to include GA tracking.  After you merge the pull request, I'll check to make sure that GA is tracking this site as expected.
Thank you!
Sarah
=> added Google Analytics tracking code to enable cross-domain tracking

R/seed.R
This will fix an issue with `use_session_with_seed` in `tensorflow`.
=> after 2.0 we should not set session.

R/model-persistence.R
=> fix serialize_model bug with plaidml

R/preprocessing.R
Addition of the description of the multi_output option for flow_images_from_dataframe() in the documentation.
=> Addition to the documentation

R/layer-text_vectorization.R, man/KerasCallback.Rd, man/KerasConstraint.Rd, man/KerasLayer.Rd, man/KerasWrapper.Rd, man/backend.Rd, man/flow_images_from_dataframe.Rd, man/layer_gru.Rd, man/layer_lstm.Rd, man/layer_simple_rnn.Rd, man/layer_text_vectorization.Rd, man/loss_binary_crossentropy.Rd, man/reexports.Rd, tests/testthat/test-layer-text_vectorization.R
=> Text vectorization tfidf

R/history.R, R/model.R, tests/testthat/test-history.R
=> As.data.frame.history

R/model-persistence.R
Cf https://github.com/rstudio/keras/issues/1167
=> Documentation load_model mention dict()

.github/workflows/main.yaml, R/Layer.R, R/layer-text_vectorization.R
Just small fixes to support tf 2.4.
Also added to CI
=> A few fixes for tf 2.4

R/utils.R, man/get_file.Rd, man/save_model_hdf5.Rd, man/save_model_tf.Rd, man/serialize_model.Rd
=> Add untar argument

tests/testthat/test-model.R
=> add test for using custom python functions

inst/python/kerastools/layer.py, inst/python/kerastools/wrapper.py, tests/testthat/test-custom-layers.R
=> Fix timedistributed custom

R/layers-core.R, man/layer_input.Rd, tests/testthat/test-layers.R
=> Adds ragged argument to layer_input

.github/workflows/main.yaml, R/model.R, tests/testthat/test-model.R
=> Fixes bug when using a generator in the validation data

.github/workflows/main.yaml, R/package.R, R/py-classes.R, tests/testthat/helper-utils.R, tests/testthat/test-callbacks.R, tests/testthat/test-py-classes.R
=> impl convert=FALSE in r_to_py.R6ClassGenerator()

DESCRIPTION, NEWS.md, R/py-classes.R, man/grapes-py_class-grapes.Rd, vignettes/guides/customizing_what_happens_in_fit.Rmd, vignettes/guides/writing_your_own_callbacks.Rmd, vignettes/python_subclasses.Rmd, website/articles/examples/nmt_attention.html, website/articles/examples/unet.html, website/articles/examples/unet_linux.html, website/articles/guides/customizing_what_happens_in_fit.html, website/pkgdown.yml, website/reference/compile.keras.engine.training.Model.html, website/reference/install_keras.html
New vignette: writing your own callbacks (using %py_class%). Includes an example of a custom learning rate scheduler.
Added support for `__doc__` strings in %py_class% (both the class and individual methods.
=> New guides

DESCRIPTION, NEWS.md, R/optimizers.R, R/utils.R, man/optimizer_adadelta.Rd, man/optimizer_adagrad.Rd, man/optimizer_adam.Rd, man/optimizer_adamax.Rd, man/optimizer_nadam.Rd, man/optimizer_rmsprop.Rd, man/optimizer_sgd.Rd, tests/testthat/test-generators.R, tools/experimental-make-wrappers.R, tools/experimental-utils.R, vignettes/guides/customizing_what_happens_in_fit.Rmd, vignettes/guides/writing_your_own_callbacks.Rmd
This patch also updates all the optimizers to use `learning_rate` instead of `lr`.
=> Vignette edits

R/preprocessing.R, man/image_dataset_from_directory.Rd, man/install_keras.Rd, man/keras.Rd
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> Support subset=both in image_dataset_from_directory()

.github/workflows/R-CMD-check.yaml, DESCRIPTION, tools/find-api-diffs.R
Initial sweep for TF 2.14 compatibility. Mostly CI updates.
=> Support for TF/Keras 2.14

NEWS.md, R/model-training.R, R/ops.R, R/utils.R
=> Accept factors in `to_categorical()`

NEWS.md, R/install.R
Resolves issue reported in https://github.com/rstudio/keras3/issues/1456
=> fix 'GPU not found' on Windows WSL Linux

.tether/vignettes-src/distribution.Rmd, .tether/vignettes-src/parked/_custom_train_step_in_torch.Rmd, .tether/vignettes-src/parked/_writing_a_custom_training_loop_in_jax.Rmd, .tether/vignettes-src/writing_your_own_callbacks.Rmd, vignettes-src/distribution.Rmd, vignettes-src/parked/_custom_train_step_in_torch.Rmd, vignettes-src/parked/_writing_a_custom_training_loop_in_jax.Rmd
=> retether vignettes

R/image-utils.R, R/r-utils.R
=> `image_load()`: coerce `target_size` correctly
